# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# MainWindow.py
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QDialog, QMessageBox
from PyQt6.QtCore import Qt
import sqlite3
from datetime import datetime, date

# ---- pliki z logiką/bazą/CSV: ----
from database import (
    pobierz_szafki, dodaj_szafke, edytuj_szafke, usun_szafke
)

# ---- pliki wygenerowane przez pyuic6 ----
from DodawanieSzafek import Ui_DodajSzafki
from DodajPracownika import Ui_Dialog
from pracownicy import DF_PRACOWNICY

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1850, 950)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SzafkiWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.SzafkiWidget.setGeometry(QtCore.QRect(0, 0, 1800, 811))
        self.SzafkiWidget.setObjectName("SzafkiWidget")
        self.SzafkiTab = QtWidgets.QWidget()
        self.SzafkiTab.setObjectName("SzafkiTab")
        self.TabelaSzafek = QtWidgets.QTableWidget(parent=self.SzafkiTab)
        self.TabelaSzafek.setGeometry(QtCore.QRect(10, 90, 1750, 900))
        self.TabelaSzafek.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AllEditTriggers)
        self.TabelaSzafek.setRowCount(0)
        self.TabelaSzafek.setObjectName("TabelaSzafek")
        self.TabelaSzafek.setColumnCount(13)
        self.PrzydzielSz = QtWidgets.QPushButton(parent=self.SzafkiTab)
        self.PrzydzielSz.setGeometry(QtCore.QRect(1160, 50, 101, 31))
        self.PrzydzielSz.setObjectName("PrzydzielSz")
        self.EdytujSz = QtWidgets.QPushButton(parent=self.SzafkiTab)
        self.EdytujSz.setGeometry(QtCore.QRect(1260, 50, 101, 31))
        self.EdytujSz.setObjectName("EdytujSz")
        self.ZwolnijSz = QtWidgets.QPushButton(parent=self.SzafkiTab)
        self.ZwolnijSz.setGeometry(QtCore.QRect(1360, 50, 101, 31))
        self.ZwolnijSz.setObjectName("ZwolnijSz")
        self.MiejsceCB = QtWidgets.QComboBox(parent=self.SzafkiTab)
        self.MiejsceCB.setEnabled(False)
        self.MiejsceCB.setGeometry(QtCore.QRect(10, 40, 161, 31))
        self.MiejsceCB.setObjectName("MiejsceCB")
        self.DodajSz = QtWidgets.QPushButton(parent=self.SzafkiTab)
        self.DodajSz.setGeometry(QtCore.QRect(1060, 50, 101, 31))
        self.DodajSz.setObjectName("DodajSz")
        self.label_6 = QtWidgets.QLabel(parent=self.SzafkiTab)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 40, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.SzafkiTab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 391, 81))
        self.groupBox.setObjectName("groupBox")
        self.SortWolne = QtWidgets.QCheckBox(parent=self.groupBox)
        self.SortWolne.setGeometry(QtCore.QRect(260, 50, 117, 20))
        self.SortWolne.setObjectName("SortWolne")
        self.NrSz = QtWidgets.QLineEdit(parent=self.groupBox)
        self.NrSz.setGeometry(QtCore.QRect(180, 40, 71, 31))
        self.NrSz.setObjectName("NrSz")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(180, 20, 45, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox.raise_()
        self.TabelaSzafek.raise_()
        self.PrzydzielSz.raise_()
        self.EdytujSz.raise_()
        self.ZwolnijSz.raise_()
        self.MiejsceCB.raise_()
        self.DodajSz.raise_()
        self.label_6.raise_()
        self.SzafkiWidget.addTab(self.SzafkiTab, "")
        self.PracownicyTab = QtWidgets.QWidget()
        self.PracownicyTab.setObjectName("PracownicyTab")
        self.PrzydzielSzPr = QtWidgets.QPushButton(parent=self.PracownicyTab)
        self.PrzydzielSzPr.setGeometry(QtCore.QRect(1210, 50, 121, 31))
        self.PrzydzielSzPr.setObjectName("PrzydzielSzPr")
        self.TabelaPracownikow = QtWidgets.QTableWidget(parent=self.PracownicyTab)
        self.TabelaPracownikow.setGeometry(QtCore.QRect(10, 90, 1750, 900))
        self.TabelaPracownikow.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AllEditTriggers)
        self.TabelaPracownikow.setDragDropOverwriteMode(True)
        self.TabelaPracownikow.setObjectName("TabelaPracownikow")
        self.TabelaPracownikow.setColumnCount(10)
        self.TabelaPracownikow.setRowCount(0)
        self.UsunPr = QtWidgets.QPushButton(parent=self.PracownicyTab)
        self.UsunPr.setGeometry(QtCore.QRect(1340, 50, 121, 31))
        self.UsunPr.setObjectName("UsunPr")
        self.NazwiskoPr = QtWidgets.QLineEdit(parent=self.PracownicyTab)
        self.NazwiskoPr.setGeometry(QtCore.QRect(10, 40, 121, 31))
        self.NazwiskoPr.setObjectName("NazwiskoPr")
        self.ImiePr = QtWidgets.QLineEdit(parent=self.PracownicyTab)
        self.ImiePr.setGeometry(QtCore.QRect(140, 40, 121, 31))
        self.ImiePr.setObjectName("ImiePr")
        self.PlecPr = QtWidgets.QLineEdit(parent=self.PracownicyTab)
        self.PlecPr.setGeometry(QtCore.QRect(530, 40, 121, 31))
        self.PlecPr.setObjectName("PlecPr")
        self.label = QtWidgets.QLabel(parent=self.PracownicyTab)
        self.label.setGeometry(QtCore.QRect(10, 20, 50, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.PracownicyTab)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 23, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.PracownicyTab)
        self.label_5.setGeometry(QtCore.QRect(530, 20, 22, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.PracownicyTab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 661, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.DzialPr = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.DzialPr.setGeometry(QtCore.QRect(270, 40, 121, 31))
        self.DzialPr.setObjectName("DzialPr")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(270, 20, 25, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(400, 20, 60, 16))
        self.label_3.setObjectName("label_3")
        self.StanowiskoPr = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.StanowiskoPr.setGeometry(QtCore.QRect(400, 40, 121, 31))
        self.StanowiskoPr.setObjectName("StanowiskoPr")
        self.groupBox_2.raise_()
        self.PrzydzielSzPr.raise_()
        self.TabelaPracownikow.raise_()
        self.UsunPr.raise_()
        self.NazwiskoPr.raise_()
        self.ImiePr.raise_()
        self.PlecPr.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.SzafkiWidget.addTab(self.PracownicyTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SzafkiWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.MiejsceCB, self.NrSz)
        MainWindow.setTabOrder(self.NrSz, self.SortWolne)
        MainWindow.setTabOrder(self.SortWolne, self.DodajSz)
        MainWindow.setTabOrder(self.DodajSz, self.PrzydzielSz)
        MainWindow.setTabOrder(self.PrzydzielSz, self.EdytujSz)
        MainWindow.setTabOrder(self.EdytujSz, self.ZwolnijSz)
        MainWindow.setTabOrder(self.ZwolnijSz, self.SzafkiWidget)
        MainWindow.setTabOrder(self.SzafkiWidget, self.NazwiskoPr)
        MainWindow.setTabOrder(self.NazwiskoPr, self.ImiePr)
        MainWindow.setTabOrder(self.ImiePr, self.StanowiskoPr)
        MainWindow.setTabOrder(self.DzialPr, self.PlecPr)
        MainWindow.setTabOrder(self.StanowiskoPr, self.DzialPr)
        MainWindow.setTabOrder(self.PlecPr, self.PrzydzielSzPr)
        MainWindow.setTabOrder(self.PrzydzielSzPr, self.UsunPr)
        MainWindow.setTabOrder(self.UsunPr, self.TabelaPracownikow)
        MainWindow.setTabOrder(self.TabelaPracownikow, self.TabelaSzafek)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zarządzanie Szafkami"))
        self.SzafkiWidget.setWhatsThis(_translate("MainWindow", "Zarządzanie szafkami"))
        self.TabelaSzafek.setWhatsThis(_translate("MainWindow", "Tabela szafek"))
        self.TabelaSzafek.setSortingEnabled(True)
        self.PrzydzielSz.setWhatsThis(_translate("MainWindow", "Przydzielanie szafki do pracownika"))
        self.PrzydzielSz.setText(_translate("MainWindow", "Przydziel szafkę"))
        self.EdytujSz.setWhatsThis(_translate("MainWindow", "Edytowanie informacji o szafce (właściciel, uwagi, numer, zamek...)"))
        self.EdytujSz.setText(_translate("MainWindow", "Edytuj szafkę"))
        self.ZwolnijSz.setWhatsThis(_translate("MainWindow", "Zwalnianie szafki przez pracownika"))
        self.ZwolnijSz.setText(_translate("MainWindow", "Zwolnij szafkę"))
        self.MiejsceCB.setWhatsThis(_translate("MainWindow", "Pole wyboru lokalizacji szafek"))
        self.DodajSz.setWhatsThis(_translate("MainWindow", "Dodawanie szafki pustej lub z pracownikiem"))
        self.DodajSz.setText(_translate("MainWindow", "Dodaj szafkę"))
        self.label_6.setText(_translate("MainWindow", "Miejsce"))
        self.groupBox.setTitle(_translate("MainWindow", "Filtry"))
        self.SortWolne.setWhatsThis(_translate("MainWindow", "Filtruje listę tylko do szafek ze statusem \"wolna\""))
        self.SortWolne.setText(_translate("MainWindow", "Tylko wolne szafki"))
        self.NrSz.setWhatsThis(_translate("MainWindow", "Filtrowanie listy po numerze szafki"))
        self.label_8.setText(_translate("MainWindow", "Nr szafki"))
        self.SzafkiWidget.setTabText(self.SzafkiWidget.indexOf(self.SzafkiTab), _translate("MainWindow", "Szafki"))
        self.PrzydzielSzPr.setWhatsThis(_translate("MainWindow", "Przydzielanie szafki do pracownika"))
        self.PrzydzielSzPr.setText(_translate("MainWindow", "Przydziel szafkę"))
        self.TabelaPracownikow.setWhatsThis(_translate("MainWindow", "Tabela szafek"))
        self.UsunPr.setWhatsThis(_translate("MainWindow", "Zwolnij wszystkie szafki zaznaczonego pracownika (np. w przypadku zakończenia współpracy)"))
        self.UsunPr.setText(_translate("MainWindow", "Zwolnij wszystkie"))
        self.NazwiskoPr.setWhatsThis(_translate("MainWindow", "Filtruje listę wg nazwiska"))
        self.ImiePr.setWhatsThis(_translate("MainWindow", "Filtruje listę wg imienia"))
        self.PlecPr.setWhatsThis(_translate("MainWindow", "Filtruje listę wg płci"))
        self.label.setText(_translate("MainWindow", "Nazwisko"))
        self.label_2.setText(_translate("MainWindow", "Imię"))
        self.label_5.setText(_translate("MainWindow", "Płeć"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filtry"))
        self.DzialPr.setWhatsThis(_translate("MainWindow", "Filtruje listę wg działu"))
        self.label_4.setText(_translate("MainWindow", "Dział"))
        self.label_3.setText(_translate("MainWindow", "Stanowisko"))
        self.StanowiskoPr.setWhatsThis(_translate("MainWindow", "Filtruje listę wg stanowiska"))
        self.SzafkiWidget.setTabText(self.SzafkiWidget.indexOf(self.PracownicyTab), _translate("MainWindow", "Pracownicy"))

class NowiPracownicyDialog(QDialog):
    def __init__(self, df_new, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Nowi pracownicy (bez szafki)")
        self.resize(900, 500)

        layout = QtWidgets.QVBoxLayout(self)

        count = len(df_new)
        info = QtWidgets.QLabel(f"Znaleziono: {count} aktywnych pracowników bez przypisanej szafki.")
        layout.addWidget(info)

        table = QtWidgets.QTableWidget(self)
        layout.addWidget(table)

        cols = ["Kod", "Nazwisko", "Imię", "Dział", "Stanowisko", "Płeć", "Data_zatrudnienia", "Data_zwolnienia"]
        table.setColumnCount(len(cols))
        table.setHorizontalHeaderLabels(cols)
        table.setRowCount(count)

        for r in range(count):
            row = df_new.iloc[r]
            for c, col in enumerate(cols):
                val = "" if col not in row or row[col] is None else str(row[col])
                item = QtWidgets.QTableWidgetItem(val)
                item.setFlags(item.flags() & ~Qt.ItemFlag.ItemIsEditable)
                table.setItem(r, c, item)

        table.resizeColumnsToContents()

        btn_close = QtWidgets.QPushButton("Zamknij")
        btn_close.clicked.connect(self.accept)
        layout.addWidget(btn_close)

class OknoGlowne(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        self._init_panel_szafek_pracownika()

        self.NowiPracownicyBt = QtWidgets.QPushButton(self.PracownicyTab)
        self.NowiPracownicyBt.setText("Nowi pracownicy")
        self.NowiPracownicyBt.setGeometry(QtCore.QRect(1465, 50, 140, 31))
        self.NowiPracownicyBt.clicked.connect(lambda: self.sprawdz_nowych_pracownikow(pokaz_zawsze=True))

        self._apply_responsive_layouts()

        self.inicjuj_signaly()
        self.zaladuj_szafki_do_tabeli()
        self.zaladuj_pracownikow_do_tabeli()
        self.sprawdz_nowych_pracownikow(pokaz_zawsze=False)

    def _apply_responsive_layouts(self):
        # --- central widget: TabWidget na cały obszar ---
        cw = self.centralwidget
        if cw.layout() is None:
            lay = QtWidgets.QVBoxLayout(cw)
            lay.setContentsMargins(0, 0, 0, 0)
            lay.addWidget(self.SzafkiWidget)

        # --- SZAFKI TAB ---
        self._layout_szafki_tab()

        # --- PRACOWNICY TAB (z panelem) ---
        self._layout_pracownicy_tab()


    def _layout_szafki_tab(self):
        tab = self.SzafkiTab
        root = QtWidgets.QVBoxLayout(tab)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(8)

        top = QtWidgets.QHBoxLayout()
        top.setSpacing(8)

        top.addWidget(self.groupBox)      # filtry
        top.addStretch(1)

        btns = QtWidgets.QHBoxLayout()
        btns.setSpacing(8)
        btns.addWidget(self.DodajSz)
        btns.addWidget(self.PrzydzielSz)
        btns.addWidget(self.EdytujSz)
        btns.addWidget(self.ZwolnijSz)
        top.addLayout(btns)

        root.addLayout(top)
        root.addWidget(self.TabelaSzafek, 1)  # 1 = stretch

    def _layout_pracownicy_tab(self):
        tab = self.PracownicyTab
        root = QtWidgets.QVBoxLayout(tab)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(8)

        top = QtWidgets.QHBoxLayout()
        top.setSpacing(8)

        top.addWidget(self.groupBox_2)    # filtry
        top.addStretch(1)

        btns = QtWidgets.QHBoxLayout()
        btns.setSpacing(8)
        btns.addWidget(self.PrzydzielSzPr)
        btns.addWidget(self.UsunPr)       # "Zwolnij wszystkie"
        btns.addWidget(self.NowiPracownicyBt)
        top.addLayout(btns)

        root.addLayout(top)

        split = QtWidgets.QSplitter(Qt.Orientation.Horizontal, tab)
        split.addWidget(self.TabelaPracownikow)
        split.addWidget(self.PanelSzafekPr)  # panel szafek pracownika

        split.setStretchFactor(0, 3)  # lewa część większa
        split.setStretchFactor(1, 2)

        root.addWidget(split, 1)

    def _init_panel_szafek_pracownika(self):
        top_y = 90
        margin = 10
        panel_h = max(300, self.SzafkiWidget.height() - top_y - margin)

        # Tabela po lewej
        self.TabelaPracownikow.setGeometry(QtCore.QRect(10, top_y, 1180, panel_h))

        # Panel po prawej
        self.PanelSzafekPr = QtWidgets.QGroupBox(self.PracownicyTab)
        self.PanelSzafekPr.setTitle("Szafki pracownika")
        self.PanelSzafekPr.setGeometry(QtCore.QRect(1200, top_y, 560, panel_h))

        lay = QtWidgets.QVBoxLayout(self.PanelSzafekPr)

        self.LblPracownikInfo = QtWidgets.QLabel("Wybierz pracownika z tabeli po lewej.")
        self.LblPracownikInfo.setWordWrap(True)
        lay.addWidget(self.LblPracownikInfo)

        self.TabelaSzafekPr = QtWidgets.QTableWidget(self.PanelSzafekPr)
        self.TabelaSzafekPr.setColumnCount(4)
        self.TabelaSzafekPr.setHorizontalHeaderLabels(["Miejsce", "Nr szafki", "Nr zamka", "ID"])
        self.TabelaSzafekPr.setColumnHidden(3, True)
        self.TabelaSzafekPr.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.TabelaSzafekPr.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.TabelaSzafekPr.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        lay.addWidget(self.TabelaSzafekPr)

        # --- PRZYCISKI NA DOLE (widoczne) ---
        btn_row = QtWidgets.QHBoxLayout()
        self.BtnZwolnijWybranaSz = QtWidgets.QPushButton("Zwolnij zaznaczoną szafkę")
        self.BtnSkoczDoSzafki = QtWidgets.QPushButton("Pokaż w zakładce Szafki")
        btn_row.addWidget(self.BtnZwolnijWybranaSz)
        btn_row.addWidget(self.BtnSkoczDoSzafki)
        lay.addLayout(btn_row)

        # pewność, że tabela ma stretch, a przyciski mają swoje miejsce
        lay.setStretch(0, 0)  # label
        lay.setStretch(1, 1)  # tabela
        lay.setStretch(2, 0)  # przyciski

        self.BtnZwolnijWybranaSz.clicked.connect(self._zwolnij_szafke_z_panelu)
        self.BtnSkoczDoSzafki.clicked.connect(self._skocz_do_szafki_w_zakladce)

        self.TabelaPracownikow.itemSelectionChanged.connect(self._odswiez_panel_szafek_pracownika)

    def _selected_employee_code(self) -> str:
        w = self.TabelaPracownikow.currentRow()
        if w < 0:
            return ""
        item = self.TabelaPracownikow.item(w, 0)
        return (item.text() if item else "").strip()


    def _odswiez_panel_szafek_pracownika(self):
        kod = self._selected_employee_code()
        if not kod:
            self.LblPracownikInfo.setText("Wybierz pracownika z tabeli po lewej.")
            self.TabelaSzafekPr.setRowCount(0)
            return
        # opis pracownika
        nazw = self.TabelaPracownikow.item(self.TabelaPracownikow.currentRow(), 1).text()
        im   = self.TabelaPracownikow.item(self.TabelaPracownikow.currentRow(), 2).text()

        szafki = (getattr(self, "_szafki_by_kod", {}) or {}).get(kod, [])

        self.LblPracownikInfo.setText(
            f"<b>{kod}</b> — {nazw} {im}<br>"
            f"Przypisane szafki: <b>{len(szafki)}</b>"
        )

        self.TabelaSzafekPr.setRowCount(len(szafki))
        for i, s in enumerate(szafki):
            self.TabelaSzafekPr.setItem(i, 0, QtWidgets.QTableWidgetItem(s.get("miejsce","")))
            self.TabelaSzafekPr.setItem(i, 1, QtWidgets.QTableWidgetItem(s.get("nr_szafki","")))
            self.TabelaSzafekPr.setItem(i, 2, QtWidgets.QTableWidgetItem(s.get("nr_zamka","")))
            self.TabelaSzafekPr.setItem(i, 3, QtWidgets.QTableWidgetItem(str(s.get("id",""))))

        self.TabelaSzafekPr.resizeColumnsToContents()


    def _zwolnij_szafke_z_panelu(self):
        r = self.TabelaSzafekPr.currentRow()
        if r < 0:
            QMessageBox.warning(self, "Brak zaznaczenia", "Zaznacz szafkę w panelu po prawej.")
            return
        id_item = self.TabelaSzafekPr.item(r, 3)
        if not id_item or not id_item.text().strip():
            return
        id_sz = int(id_item.text().strip())

        potw = QMessageBox.question(
            self, "Potwierdź",
            f"Zwolnić szafkę (ID={id_sz}) z tego pracownika?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )
        if potw != QMessageBox.StandardButton.Yes:
            return

        # znajdź rekord w DB i wyczyść
        for row in pobierz_szafki():
            if row and len(row) >= 14 and row[0] == id_sz:
                edytuj_szafke(
                    id_szafki=row[0],
                    miejsce=row[1],
                    nr_szafki=row[2],
                    nr_zamka=row[3],
                    plec_szatni=row[4],
                    kod_pracownika="",
                    nazwisko="",
                    imie="",
                    dzial="",
                    stanowisko="",
                    plec="",
                    zmiana="",
                    status="Wolna",
                    komentarz=(row[13] or "")
                )
                break

        self.zaladuj_szafki_do_tabeli()
        self.zaladuj_pracownikow_do_tabeli()
        self._odswiez_panel_szafek_pracownika()


    def _skocz_do_szafki_w_zakladce(self):
        r = self.TabelaSzafekPr.currentRow()
        if r < 0:
            return
        id_item = self.TabelaSzafekPr.item(r, 3)
        if not id_item:
            return
        id_sz = id_item.text().strip()
        if not id_sz:
            return
        # przełącz na zakładkę Szafki
        self.SzafkiWidget.setCurrentIndex(0)

        # znajdź w tabeli szafek wiersz o ID i zaznacz
        for i in range(self.TabelaSzafek.rowCount()):
            it = self.TabelaSzafek.item(i, 0)
            if it and it.text().strip() == id_sz:
                self.TabelaSzafek.selectRow(i)
                self.TabelaSzafek.scrollToItem(self.TabelaSzafek.item(i, 1))
                break

    def _map_szafki_by_kod(self) -> dict[str, list[dict]]:
        """
        kod_pracownika -> lista szafek (tylko zajęte; wolne pomijamy)
        """
        rows = getattr(self, "_wszystkie_szafki", None) or pobierz_szafki()
        m: dict[str, list[dict]] = {}

        for r in rows:
            if not r or len(r) < 14:
                continue

            kod = str(r[5] or "").strip()
            status = str(r[12] or "").strip()
            if not kod:
                continue
            if status == "Wolna":
                continue

            m.setdefault(kod, []).append({
                "id": r[0],
                "miejsce": str(r[1] or "").strip(),
                "nr_szafki": str(r[2] or "").strip(),
                "nr_zamka": str(r[3] or "").strip(),
                "plec_szatni": str(r[4] or "").strip(),
                "status": status,
                "komentarz": str(r[13] or "").strip(),
                })
        return m

    def _parse_pl_date(self, s: str):
        if s is None:
            return None
        s = str(s).strip()
        if not s:
            return None
        try:
            return datetime.strptime(s, "%d.%m.%Y").date()
        except ValueError:
            return None

    def _is_active_employee(self, kod: str) -> bool:
        kod = (kod or "").strip()
        if not kod:
            return False
        if kod not in DF_PRACOWNICY.index:
            return False
        zw = DF_PRACOWNICY.loc[kod].get("Data_zwolnienia", "")
        zw = "" if zw is None else str(zw).strip()

        # aktywny = brak daty zwolnienia
        return zw == ""
    
    def _assigned_codes_from_db(self) -> set[str]:
        # użyj już pobranych danych jeśli są
        rows = getattr(self, "_wszystkie_szafki", None) or pobierz_szafki()

        codes = set()
        for row in rows:
            kod = str(row[5] or "").strip()   # kod_pracownika
            status = str(row[12] or "").strip()  # status
            if kod and status != "Wolna":
                codes.add(kod)
        return codes

    def sprawdz_nowych_pracownikow(self, *, pokaz_zawsze=False):
        assigned = self._assigned_codes_from_db()

        active_codes = [kod for kod in DF_PRACOWNICY.index if self._is_active_employee(kod)]
        new_codes = sorted(set(active_codes) - assigned)
    
        if not new_codes:
            if pokaz_zawsze:
                QMessageBox.information(self, "Nowi pracownicy", "Nie znaleziono nowych aktywnych pracowników bez szafki.")
            return

        df_new = DF_PRACOWNICY.loc[new_codes].reset_index()  # index=Kod -> kolumna "Kod"
        dlg = NowiPracownicyDialog(df_new, parent=self)
        dlg.exec()

    def _zwolnij_wszystkie_szafki_pracownika(self):
        kod = self._selected_employee_code()
        if not kod:
            QMessageBox.warning(self, "Brak pracownika", "Wybierz pracownika z tabeli po lewej.")
            return

        szafki = (getattr(self, "_szafki_by_kod", {}) or {}).get(kod, [])
        if not szafki:
            QMessageBox.information(self, "Brak szafek", "Ten pracownik nie ma przypisanych szafek.")
            return

        potw = QMessageBox.question(
            self,
            "Potwierdź",
            f"Zwolnić WSZYSTKIE szafki pracownika {kod}? (liczba: {len(szafki)})",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )
        if potw != QMessageBox.StandardButton.Yes:
            return

        ids = {int(s["id"]) for s in szafki if str(s.get("id", "")).strip().isdigit()}

        for row in pobierz_szafki():
            if not row or len(row) < 14:
                continue
            if row[0] in ids:
                edytuj_szafke(
                    id_szafki=row[0],
                    miejsce=row[1],
                    nr_szafki=row[2],
                    nr_zamka=row[3],
                    plec_szatni=row[4],
                    kod_pracownika="",
                    nazwisko="",
                    imie="",
                    dzial="",
                    stanowisko="",
                    plec="",
                    zmiana="",
                    status="Wolna",
                    komentarz=(row[13] or "")
                )

        self.zaladuj_szafki_do_tabeli()
        self.zaladuj_pracownikow_do_tabeli()
        self._odswiez_panel_szafek_pracownika()

    def inicjuj_signaly(self):
        print("inicjuj_signaly() – podpinam przyciski i filtry.")
        # Zakładka "Szafki"
        self.DodajSz.clicked.connect(self.on_dodaj_szafke)
        self.EdytujSz.clicked.connect(self.on_edytuj_szafke)
        self.ZwolnijSz.clicked.connect(self.on_zwolnij_szafke)
        self.PrzydzielSz.clicked.connect(self.on_przydziel_szafke)
        self.SortWolne.stateChanged.connect(self.filtruj_tabele_szafek)
        self.MiejsceCB.currentIndexChanged.connect(self.filtruj_tabele_szafek)
        self.NrSz.textChanged.connect(self.filtruj_tabele_szafek)

        # Zakładka "Pracownicy"
        self.PrzydzielSzPr.clicked.connect(self.on_przydziel_szafke_pracownikowi)
        self.UsunPr.clicked.connect(self._zwolnij_wszystkie_szafki_pracownika)
        self.NazwiskoPr.textChanged.connect(self.filtruj_tabele_pracownikow)
        self.ImiePr.textChanged.connect(self.filtruj_tabele_pracownikow)
        self.PlecPr.textChanged.connect(self.filtruj_tabele_pracownikow)
        self.DzialPr.textChanged.connect(self.filtruj_tabele_pracownikow)
        self.StanowiskoPr.textChanged.connect(self.filtruj_tabele_pracownikow)

    # -------------- OBSŁUGA TABELI "SZAFKI" --------------
    def zaladuj_szafki_do_tabeli(self):
        print("zaladuj_szafki_do_tabeli()")
        self._wszystkie_szafki = pobierz_szafki()

        # --- UZUPEŁNIANIE COMBOBOXA "Miejsce" ---
        miejsca = sorted(set(row[1] for row in self._wszystkie_szafki if row[1]))
        self.MiejsceCB.blockSignals(True)  # żeby nie wywoływać filtracji przy każdym dodaniu
        self.MiejsceCB.clear()
        self.MiejsceCB.addItem("")  # opcja "wszystkie"
        self.MiejsceCB.addItems(miejsca)
        self.MiejsceCB.setEnabled(True)
        self.MiejsceCB.blockSignals(False)

        self.filtruj_tabele_szafek()

    # --------------------------------------------------#
    #                OBSŁUGA TABELI "SZAFKI"            #
    # --------------------------------------------------#

    def filtruj_tabele_szafek(self):
        """
        Na podstawie _wszystkie_szafki oraz wybranych filtrów
        pokazujemy w TabelaSzafek tylko te wiersze, które pasują.
        """
        if not hasattr(self, '_wszystkie_szafki'):
            return

        miejsce_filtr = self.MiejsceCB.currentText().strip()
        nr_filtr = self.NrSz.text().strip()
        tylko_wolne = self.SortWolne.isChecked()

        # Przykład prostego filtrowania w pythonie:
        lista_filtrowana = []
        for row in self._wszystkie_szafki:
            (id_sz, miejsce, nr_sz, nr_zamka, plec_szat, kod_prac, nazw, imie, dzial, stan, plec, zm, status, komentarz) = row
            # Filtr Miejsce
            if miejsce_filtr and miejsce_filtr != miejsce:
                continue

            # Filtr Nr szafki (jeśli wprowadzony)
            if nr_filtr:
                if not str(nr_sz).startswith(nr_filtr):
                    continue

            # Filtr Tylko wolne
            if tylko_wolne and status != "Wolna":
                continue

            lista_filtrowana.append(row)

        # Teraz aktualizujemy TabelaSzafek
        self._wyswietl_szafki_w_tabeli(lista_filtrowana)

    def _wyswietl_szafki_w_tabeli(self, lista_szafek):
        """
        Ustawia w TabelaSzafek wiersze z listy lista_szafek.
        """
        self.TabelaSzafek.clear()
        self.TabelaSzafek.setColumnCount(14)
        self.TabelaSzafek.setRowCount(len(lista_szafek))

        naglowki = [
            "ID", "Miejsce", "Nr szafki", "Nr zamka", "Płeć szatni", "Kod prac.", "Nazwisko", "Imię", "Dział", "Stanowisko", "Płeć", "Zmiana", "Status", "Komentarz"
        ]
        self.TabelaSzafek.setHorizontalHeaderLabels(naglowki)

        for i, row in enumerate(lista_szafek):
            wartosci = [
                row[0],  # ID szafki
                row[1],  # Miejsce
                row[2],  # Nr szafki
                row[3],  # Nr zamka
                row[4],  # Płeć szatni
                row[5],  # Kod pracownika
                row[6],  # Nazwisko
                row[7],  # Imię
                row[8],  # Dział
                row[9],  # Stanowisko
                row[10], # Płeć
                row[11], # Zmiana
                row[12], # Status
                row[13], # Komentarz
            ]
            for j, val in enumerate(wartosci):
                text = str(val) if val is not None else ""
                item = QtWidgets.QTableWidgetItem(text)
                item.setFlags(item.flags() & ~Qt.ItemFlag.ItemIsEditable)
                self.TabelaSzafek.setItem(i, j, item)

        self.TabelaSzafek.resizeColumnsToContents()
        self.TabelaSzafek.setColumnHidden(0, True)

    def on_dodaj_szafke(self):
        print("on_dodaj_szafke() – klik.")
        dialog = QDialog(self)
        ui = Ui_DodajSzafki() 
        ui.setupUi(dialog)
        
        # --- UZUPEŁNIANIE COMBOBOXA "MiejsceDS" ---
        miejsca = sorted(set(row[1] for row in self._wszystkie_szafki if row[1]))
        ui.MiejsceDS.clear()
        ui.MiejsceDS.addItem("")  # opcja "wszystkie" lub puste
        ui.MiejsceDS.addItems(miejsca)

        ui.StatusSzDS.addItems(["Wolna", "Nieczynna"])
        ui.PlecDS.addItems(["Kobieta", "Mężczyzna", "Neutralna"])

        def klik_dodaj():
            print("klik_dodaj() – tworzymy nową szafkę w db")
            dodaj_szafke(
                miejsce=ui.MiejsceDS.currentText(),
                nr_szafki=int(ui.NrSzDS.text()) if ui.NrSzDS.text() else None,
                nr_zamka=int(ui.KodZDS.text()) if ui.KodZDS.text() else None,
                plec_szatni=ui.PlecDS.currentText(),
                kod_pracownika="",
                nazwisko="",
                imie="",
                dzial="",
                stanowisko="",
                plec="",
                zmiana="",
                status=ui.StatusSzDS.currentText(),
                komentarz=""
            )
            dialog.accept()

        ui.DodajBtDS.clicked.connect(klik_dodaj)

        # Pokaz dialog
        if dialog.exec() == int(QDialog.DialogCode.Accepted):
            self.zaladuj_szafki_do_tabeli()

    def on_edytuj_szafke(self):
        """
        Obsługa przycisku "Edytuj szafkę".
        Edytujemy zaznaczoną szafkę w TabelaSzafek.
        """
        wiersz = self.TabelaSzafek.currentRow()
        if wiersz < 0:
            QMessageBox.warning(self, "Brak zaznaczenia", "Zaznacz szafkę do edycji!")
            return

        # ID z kolumny 0
        id_szafki = int(self.TabelaSzafek.item(wiersz, 0).text())

        # Odczyt aktualnych wartości (dla uproszczenia - odczyt z TabelaSzafek)
        aktualne = [self.TabelaSzafek.item(wiersz, col).text() for col in range(14)]
        # Rozbijmy je:
        (_id, miejsce, nr_s, nr_z, plec_sz, kod_prac, nazw, im, dz, stan, plec, zm, stat, kom) = aktualne

        # Otwieramy dialog "DodawanieSzafek", ale w trybie edycji
        dialog = QDialog(self)
        ui = Ui_DodajSzafki()
        ui.setupUi(dialog)
        
        wynik = dialog.exec()
        if wynik == int(QDialog.DialogCode.Rejected):
            return

        # Ustawiamy wartości
        ui.MiejsceDS.setEditText(miejsce)
        ui.NrSzDS.setText(nr_s)
        ui.KodZDS.setText(nr_z)
        ui.PlecDS.addItems(["Kobieta", "Mężczyzna", "Neutralna"])
        ui.PlecDS.setCurrentText(plec_sz)
        ui.StatusSzDS.addItems(["Wolna", "Nieczynna"])
        if stat in ["Wolna", "Nieczynna"]:
            ui.StatusSzDS.setCurrentText(stat)

        validatorInt = QtGui.QIntValidator(0, 999999, self)
        ui.NrSzDS.setValidator(validatorInt)
        ui.KodZDS.setValidator(validatorInt)

        def klik_zapisz():
            nowe_miejsce = ui.MiejsceDS.currentText().strip()
            nowe_nr_s = ui.NrSzDS.text().strip()
            nowe_nr_z = ui.KodZDS.text().strip()
            nowe_plec_sz = ui.PlecDS.currentText().strip()
            nowe_status = ui.StatusSzDS.currentText().strip()

            # Edytujemy w bazie
            edytuj_szafke(
                id_szafki=id_szafki,
                miejsce=nowe_miejsce,
                nr_szafki=int(nowe_nr_s) if nowe_nr_s else None,
                nr_zamka=int(nowe_nr_z) if nowe_nr_z else None,
                plec_szatni=nowe_plec_sz,
                kod_pracownika=kod_prac,
                nazwisko=nazw,
                imie=im,
                dzial=dz,
                stanowisko=stan,
                plec=plec,
                zmiana=zm,
                status=nowe_status,
                komentarz=kom
            )
            dialog.accept()

        ui.DodajBtDS.setText("Zapisz")  # zmieniamy etykietę przycisku
        ui.DodajBtDS.clicked.connect(klik_zapisz)

        if dialog.exec() == QDialog.Accepted:
            self.zaladuj_szafki_do_tabeli()

    def on_zwolnij_szafke(self):
        """
        Ustawia status zaznaczonej szafki na 'Wolna' i czyści dane pracownika.
        """
        wiersz = self.TabelaSzafek.currentRow()
        if wiersz < 0:
            QMessageBox.warning(self, "Brak zaznaczenia", "Zaznacz szafkę do zwolnienia!")
            return

        id_szafki = int(self.TabelaSzafek.item(wiersz, 0).text())
        # Odczytujemy resztę:
        aktualne = [self.TabelaSzafek.item(wiersz, col).text() for col in range(14)]
        (_id, miejsce, nr_s, nr_z, plec_sz, kod_prac, nazw, im, dz, stan, plec, zm, stat, kom) = aktualne

        # Ustawiamy status="Wolna", czyścimy dane
        edytuj_szafke(
            id_szafki=id_szafki,
            miejsce=miejsce,
            nr_szafki=nr_s,
            nr_zamka=nr_z,
            plec_szatni=plec_sz,
            kod_pracownika="",
            nazwisko="",
            imie="",
            dzial="",
            stanowisko="",
            plec="",
            zmiana="",
            status="Wolna",
            komentarz=kom
        )
        self.zaladuj_szafki_do_tabeli()
        
    def ustaw_dozwolone_szatnie(ui):
        plec_prac = ui.PlecDP.currentText().strip().lower()
        if plec_prac == "kobieta":
            dozwolone = ["Damska", "Neutralna"]
        elif plec_prac == "mężczyzna":
            dozwolone = ["Męska", "Neutralna"]
        else:
            dozwolone = ["Neutralna"]
        ui.PlecDS.clear()
        ui.PlecDS.addItems(dozwolone)
        
    def on_przydziel_szafke(self):
        """
        Klik przycisku 'Przydziel szafkę' (zakładka Szafki).
        """
        wiersz = self.TabelaSzafek.currentRow()
        if wiersz < 0:
            QMessageBox.warning(self, "Brak zaznaczenia", "Zaznacz szafkę.")
            return

        # --- dialog QDialog z Ui_Dialog
        dialog = QDialog(self)
        ui = Ui_Dialog()
        ui.setupUi(dialog)

        # Numer szafki z zaznaczonego wiersza
        nr_szafki = self.TabelaSzafek.item(wiersz, 2).text()
        if hasattr(ui, "NrSzSzDP1"):
            ui.NrSzSzDP1.setText(nr_szafki)

        # --- UZUPEŁNIANIE COMBOBOXA ---
        ui.PlecDP.clear()
        ui.PlecDP.addItems(["Kobieta", "Mężczyzna"])
        stanowiska = sorted(set(DF_PRACOWNICY['Stanowisko'].dropna()))
        ui.StanowiskoDP.clear()
        ui.StanowiskoDP.addItems(stanowiska)
        dzialy = sorted(set(DF_PRACOWNICY['Dział'].dropna()))
        ui.DzialDP.clear()
        ui.DzialDP.addItems(dzialy)
        miejsca = sorted(set(row[1] for row in self._wszystkie_szafki if row[1]))
        ui.MiejsceDP.clear()
        ui.MiejsceDP.addItems(miejsca)

        ui.KodPracDP.textChanged.connect(lambda _: self.on_kod_changed(ui))

        wynik = dialog.exec()
        if wynik == QDialog.DialogCode.Accepted:
            self.zaladuj_szafki_do_tabeli()
    def on_losuj_wolna_szafke(self):
        """
        Losuje wolną szafkę zgodnie z płcią pracownika lub neutralną.
        """
        # Pobierz dane pracownika z dialogu lub tabeli
        plec_prac = None
        if hasattr(self, 'dialog_pracownika') and self.dialog_pracownika is not None:
            plec_prac = self.dialog_pracownika.ui.PlecDP.currentText()
        else:
            # Przykład: pobierz z zaznaczonego wiersza w tabeli pracowników
            wiersz = self.TabelaPracownikow.currentRow()
            if wiersz >= 0:
                plec_prac = self.TabelaPracownikow.item(wiersz, 3).text()
            else:
                QMessageBox.warning(self, "Brak danych", "Nie wybrano pracownika.")
                return

        # Filtruj wolne szafki o odpowiedniej płci szatni
        wolne_szafki = [
            row for row in self._wszystkie_szafki
            if row[12] == "Wolna" and (row[4] == plec_prac or row[4].lower() == "neutralna")
        ]

        if not wolne_szafki:
            QMessageBox.information(self, "Brak wolnych szafek", "Brak wolnych szafek dla tej płci lub neutralnych.")
            return

        import random
        szafka = random.choice(wolne_szafki)
        # Zaznacz w tabeli szafek wylosowaną szafkę
        for i, row in enumerate(self._wszystkie_szafki):
            if row[0] == szafka[0]:  # ID szafki
                self.SzafkiWidget.setCurrentIndex(0)  # przełącz na zakładkę szafek
                self.TabelaSzafek.selectRow(i)
                self.TabelaSzafek.scrollToItem(self.TabelaSzafek.item(i, 1))
                break

        QMessageBox.information(self, "Wylosowano szafkę", f"Wylosowano szafkę nr {szafka[2]} ({szafka[1]})")
    
    def on_usun_szafke(self):
        wiersz = self.TabelaSzafek.currentRow()
        if wiersz < 0:
            QMessageBox.warning(self, "Brak zaznaczenia", "Zaznacz szafkę do usunięcia!")
            return

        id_szafki = int(self.TabelaSzafek.item(wiersz, 0).text())
        potw = QMessageBox.question(
            self,
            "Potwierdź",
            f"Czy na pewno usunąć szafkę (ID={id_szafki})?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )

        if potw != QMessageBox.StandardButton.Yes:
            return

        usun_szafke(id_szafki)
        self.zaladuj_szafki_do_tabeli()

    # --------------------------------------------------#
    #                OBSŁUGA TABELI "PRACOWNICY"        #
    # --------------------------------------------------#

    def zaladuj_pracownikow_do_tabeli(self):
        print("zaladuj_pracownikow_do_tabeli()")
        # snapshot mapy z DB (żeby nie liczyć w kółko w pętli)
        self._szafki_by_kod = self._map_szafki_by_kod()
        self.filtruj_tabele_pracownikow()
        self._odswiez_panel_szafek_pracownika()

    def filtruj_tabele_pracownikow(self):
        nazwisko_f = self.NazwiskoPr.text().strip().lower()
        imie_f     = self.ImiePr.text().strip().lower()
        plec_f     = self.PlecPr.text().strip().lower()
        dzial_f    = self.DzialPr.text().strip().lower()
        stan_f     = self.StanowiskoPr.text().strip().lower()

        df = DF_PRACOWNICY.copy()
        df = df.reset_index()  # index=Kod -> kolumna "Kod"

        def s(x): return "" if x is None else str(x)

        lista = []
        for _, r in df.iterrows():
            kod  = s(r.get("Kod")).strip()
            nazw = s(r.get("Nazwisko")).strip()
            im   = s(r.get("Imię")).strip()
            dz   = s(r.get("Dział")).strip()
            stan = s(r.get("Stanowisko")).strip()
            plec = s(r.get("Płeć")).strip()
            dzatr = s(r.get("Data_zatrudnienia")).strip()
            dzw   = s(r.get("Data_zwolnienia")).strip()

            if nazwisko_f and nazwisko_f not in nazw.lower(): continue
            if imie_f and imie_f not in im.lower():           continue
            if plec_f and plec_f not in plec.lower():         continue
            if dzial_f and dzial_f not in dz.lower():         continue
            if stan_f and stan_f not in stan.lower():         continue

            sz_list = (getattr(self, "_szafki_by_kod", {}) or {}).get(kod, [])
            lista.append({
                "Kod": kod,
                "Nazwisko": nazw,
                "Imię": im,
                "Płeć": plec,
                "Dział": dz,
                "Stanowisko": stan,
                "Data_zatrudnienia": dzatr,
                "Data_zwolnienia": dzw,
                "Szafki_count": len(sz_list),
            })

        self._wyswietl_pracownikow_w_tabeli(lista)

    def _wyswietl_pracownikow_w_tabeli(self, lista_prac: list[dict]):
        naglowki = [
            "Kod","Nazwisko","Imię","Płeć","Dział","Stanowisko",
            "Data zatr.","Data zwol.","Szafki"
        ]

        self.TabelaPracownikow.clearContents()
        self.TabelaPracownikow.setColumnCount(len(naglowki))
        self.TabelaPracownikow.setHorizontalHeaderLabels(naglowki)
        self.TabelaPracownikow.setRowCount(len(lista_prac))

        for i, r in enumerate(lista_prac):
            wartosci = [
                r.get("Kod",""), r.get("Nazwisko",""), r.get("Imię",""), r.get("Płeć",""),
                r.get("Dział",""), r.get("Stanowisko",""),
                r.get("Data_zatrudnienia",""), r.get("Data_zwolnienia",""),
                str(r.get("Szafki_count", 0)),
            ]
            for j, val in enumerate(wartosci):
                item = QtWidgets.QTableWidgetItem(str(val))
                item.setFlags(item.flags() & ~Qt.ItemFlag.ItemIsEditable)
                self.TabelaPracownikow.setItem(i, j, item)

        self.TabelaPracownikow.resizeColumnsToContents()

    def on_przydziel_szafke_pracownikowi(self):
        print("on_przydziel_szafke_pracownikowi() – klik")

        dialog = QDialog(self)
        ui = Ui_Dialog()
        ui.setupUi(dialog)

        # comboboxy z CSV
        ui.DzialDP.clear()
        ui.DzialDP.addItems(sorted(set(DF_PRACOWNICY["Dział"].dropna())))

        ui.StanowiskoDP.clear()
        ui.StanowiskoDP.addItems(sorted(set(DF_PRACOWNICY["Stanowisko"].dropna())))

        ui.PlecDP.clear()
        ui.PlecDP.addItems(sorted(set(DF_PRACOWNICY["Płeć"].dropna())))
        ui.KodPracDP.textChanged.connect(lambda _: self.on_kod_changed(ui))
        
        # jeśli zaznaczony wiersz -> wypełnij dialog
        wiersz = self.TabelaPracownikow.currentRow()
        if wiersz >= 0:
            kod_prac = self.TabelaPracownikow.item(wiersz, 0).text().strip()
            ui.KodPracDP.setText(kod_prac)

        if dialog.exec() == QDialog.DialogCode.Accepted:
            self.zaladuj_szafki_do_tabeli()
            self.zaladuj_pracownikow_do_tabeli()