# Form implementation generated from reading ui file 'DodajPracownika2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 300)

        # Użycie vertical layout jako głównego kontenera
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.formGrid = QtWidgets.QGridLayout()
        self.formGrid.setSpacing(10)
        self.formGrid.setHorizontalSpacing(15)

        # Button box
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")

        # Wejścia formularza
        self.ImieDP = QtWidgets.QLabel(parent=Dialog)
        self.ImieDP.setObjectName("ImieDP")
        self.DzialDP = QtWidgets.QLabel(parent=Dialog)
        self.DzialDP.setObjectName("DzialDP")
        self.PlecDP = QtWidgets.QLabel(parent=Dialog)
        self.PlecDP.setObjectName("PlecDP")
        self.NazwiskoDP = QtWidgets.QLabel(parent=Dialog)
        self.NazwiskoDP.setObjectName("NazwiskoDP")
        self.KodPracDP = QtWidgets.QLineEdit(parent=Dialog)
        self.KodPracDP.setMaxLength(6)
        self.KodPracDP.setObjectName("KodPracDP")
        self.ZmianaDP = QtWidgets.QLabel(parent=Dialog)
        self.ZmianaDP.setObjectName("ZmianaDP")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(parent=Dialog)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=Dialog)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=Dialog)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.MiejsceDP = QtWidgets.QLabel(parent=Dialog)
        self.MiejsceDP.setObjectName("MiejsceDP")
        self.StanowiskoDP = QtWidgets.QLabel(parent=Dialog)
        self.StanowiskoDP.setObjectName("StanowiskoDP")
        self.DodajBtDP = QtWidgets.QPushButton(parent=Dialog)
        self.DodajBtDP.setObjectName("DodajBtDP")

        # Budowa siatki formularza
        self.formGrid.addWidget(self.label_10, 0, 0)
        self.formGrid.addWidget(self.KodPracDP, 0, 1)
        self.formGrid.addWidget(self.label_9, 0, 2)
        self.formGrid.addWidget(self.NazwiskoDP, 0, 3)
        self.formGrid.addWidget(self.label_11, 0, 4)
        self.formGrid.addWidget(self.ImieDP, 0, 5)

        self.formGrid.addWidget(self.label_7, 1, 0)
        self.formGrid.addWidget(self.PlecDP, 1, 1)
        self.formGrid.addWidget(self.label_8, 1, 2)
        self.formGrid.addWidget(self.DzialDP, 1, 3)
        self.formGrid.addWidget(self.label_6, 1, 4)
        self.formGrid.addWidget(self.StanowiskoDP, 1, 5)

        self.formGrid.addWidget(self.label_12, 2, 0)
        self.formGrid.addWidget(self.ZmianaDP, 2, 1)
        self.formGrid.addWidget(self.MiejsceDP, 2, 3)

        # Przyciski na dole
        btns = QtWidgets.QHBoxLayout()
        btns.setSpacing(10)
        btns.addStretch()
        self.DodajBtDP = QtWidgets.QPushButton(parent=Dialog)
        self.DodajBtDP.setMinimumSize(100, 35)
        self.DodajBtDP.setObjectName("DodajBtDP")
        btns.addWidget(self.DodajBtDP)
        btns.addWidget(self.buttonBox)

        self.verticalLayout.addLayout(self.formGrid)
        self.verticalLayout.addLayout(btns)

        # Kolejność tabowania:
        Dialog.setTabOrder(self.KodPracDP, self.DodajBtDP)
        Dialog.setTabOrder(self.DodajBtDP, self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # typ: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # typ: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dodawanie pracownika"))
        self.ImieDP.setWhatsThis(_translate("Dialog", "Wproszadź ilość szafek, która ma zostać dodana"))
        self.DzialDP.setWhatsThis(_translate("Dialog", "Wybór miejsca, w którym znajdować się mają szafki"))
        self.PlecDP.setWhatsThis(_translate("Dialog", "Typ dodawanych szafek"))
        self.NazwiskoDP.setWhatsThis(_translate("Dialog", "Wprowadź numer początkowej szafki (tej, od której numeru będą tworzyć się kolejne, np. 1 w przypadku, gdy tworzymy szafki od zera)"))
        self.KodPracDP.setWhatsThis(_translate("Dialog", "Wprowadź kod pracownika"))
        self.label_6.setText(_translate("Dialog", "Stanowisko"))
        self.label_8.setText(_translate("Dialog", "Dział"))
        self.label_7.setText(_translate("Dialog", "Płeć"))
        self.label_9.setText(_translate("Dialog", "Nazwisko"))
        self.label_10.setText(_translate("Dialog", "Kod pracow."))
        self.label_11.setText(_translate("Dialog", "Imię"))
        self.label_12.setText(_translate("Dialog", "Zmiana"))
        self.MiejsceDP.setWhatsThis(_translate("Dialog", "Wybór miejsca, w którym znajdować się mają szafki"))
        self.StanowiskoDP.setWhatsThis(_translate("Dialog", "Wybór miejsca, w którym znajdować się mają szafki"))
        self.DodajBtDP.setText(_translate("Dialog", "Przydziel"))