# Form implementation generated from reading ui file 'DodawanieSzafek.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DodajSzafki(object):
    def setupUi(self, DodajSzafki):
        DodajSzafki.setObjectName("DodajSzafki")
        DodajSzafki.resize(1000, 280)
        
        main_layout = QtWidgets.QVBoxLayout(DodajSzafki)
        main_layout.setContentsMargins(10, 10, 10, 10)
        main_layout.setSpacing(10)
        
        # Skrollowalny obszar z wejściami
        scroll_area = QtWidgets.QScrollArea(DodajSzafki)
        scroll_area.setWidgetResizable(True)
        scroll_widget = QtWidgets.QWidget()
        inputs_layout = QtWidgets.QVBoxLayout(scroll_widget)
        inputs_layout.setSpacing(10)
        
        # Pierwszy wiersz - Miejsce, Nr szafki, Kod zamka, Płeć, Status
        row1_layout = QtWidgets.QHBoxLayout()
        row1_layout.setSpacing(10)
        
        # Miejsce
        label_6_layout = QtWidgets.QVBoxLayout()
        self.label_6 = QtWidgets.QLabel(parent=scroll_widget)
        self.label_6.setObjectName("label_6")
        self.label_6.setText("Miejsce")
        label_6_layout.addWidget(self.label_6)
        self.MiejsceDS = QtWidgets.QComboBox(parent=scroll_widget)
        self.MiejsceDS.setAccessibleName("")
        self.MiejsceDS.setEditable(True)
        self.MiejsceDS.setObjectName("MiejsceDS")
        self.MiejsceDS.setMinimumWidth(140)
        label_6_layout.addWidget(self.MiejsceDS)
        row1_layout.addLayout(label_6_layout)
        
        # Nr szafki
        label_8_layout = QtWidgets.QVBoxLayout()
        self.label_8 = QtWidgets.QLabel(parent=scroll_widget)
        self.label_8.setObjectName("label_8")
        self.label_8.setText("Nr szafki")
        self.label_8.setWordWrap(True)
        label_8_layout.addWidget(self.label_8)
        self.NrSzDS = QtWidgets.QLineEdit(parent=scroll_widget)
        self.NrSzDS.setMaxLength(3)
        self.NrSzDS.setObjectName("NrSzDS")
        self.NrSzDS.setMaximumWidth(80)
        label_8_layout.addWidget(self.NrSzDS)
        row1_layout.addLayout(label_8_layout)
        
        # Kod zamka
        label_9_layout = QtWidgets.QVBoxLayout()
        self.label_9 = QtWidgets.QLabel(parent=scroll_widget)
        self.label_9.setObjectName("label_9")
        self.label_9.setText("Kod zamka")
        self.label_9.setWordWrap(True)
        label_9_layout.addWidget(self.label_9)
        self.KodZDS = QtWidgets.QLineEdit(parent=scroll_widget)
        self.KodZDS.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.KodZDS.setText("")
        self.KodZDS.setMaxLength(5)
        self.KodZDS.setObjectName("KodZDS")
        self.KodZDS.setMaximumWidth(80)
        label_9_layout.addWidget(self.KodZDS)
        row1_layout.addLayout(label_9_layout)
        
        # Płeć
        label_10_layout = QtWidgets.QVBoxLayout()
        self.label_10 = QtWidgets.QLabel(parent=scroll_widget)
        self.label_10.setObjectName("label_10")
        self.label_10.setText("Płeć docelowa")
        self.label_10.setWordWrap(True)
        label_10_layout.addWidget(self.label_10)
        self.PlecDS = QtWidgets.QComboBox(parent=scroll_widget)
        self.PlecDS.setEditable(False)
        self.PlecDS.setObjectName("PlecDS")
        self.PlecDS.setMinimumWidth(120)
        label_10_layout.addWidget(self.PlecDS)
        row1_layout.addLayout(label_10_layout)
        
        # Status szafki
        label_11_layout = QtWidgets.QVBoxLayout()
        self.label_11 = QtWidgets.QLabel(parent=scroll_widget)
        self.label_11.setObjectName("label_11")
        self.label_11.setText("Status szafki")
        label_11_layout.addWidget(self.label_11)
        self.StatusSzDS = QtWidgets.QComboBox(parent=scroll_widget)
        self.StatusSzDS.setEditable(False)
        self.StatusSzDS.setObjectName("StatusSzDS")
        self.StatusSzDS.setMinimumWidth(120)
        label_11_layout.addWidget(self.StatusSzDS)
        row1_layout.addLayout(label_11_layout)
        
        row1_layout.addStretch()
        inputs_layout.addLayout(row1_layout)
        
        # Drugi wiersz - Kod właściciela, Uwagi
        row2_layout = QtWidgets.QHBoxLayout()
        row2_layout.setSpacing(10)
        
        # Kod właściciela
        label_kod_layout = QtWidgets.QVBoxLayout()
        self.label_kod = QtWidgets.QLabel(parent=scroll_widget)
        self.label_kod.setObjectName("label_kod")
        self.label_kod.setText("Kod właściciela")
        label_kod_layout.addWidget(self.label_kod)
        self.KodWlascicelaDS = QtWidgets.QLineEdit(parent=scroll_widget)
        self.KodWlascicelaDS.setObjectName("KodWlascicelaDS")
        self.KodWlascicelaDS.setMinimumWidth(140)
        label_kod_layout.addWidget(self.KodWlascicelaDS)
        row2_layout.addLayout(label_kod_layout)
        
        # Uwagi
        label_uwagi_layout = QtWidgets.QVBoxLayout()
        self.label_uwagi = QtWidgets.QLabel(parent=scroll_widget)
        self.label_uwagi.setObjectName("label_uwagi")
        self.label_uwagi.setText("Uwagi")
        label_uwagi_layout.addWidget(self.label_uwagi)
        self.UwagiDS = QtWidgets.QLineEdit(parent=scroll_widget)
        self.UwagiDS.setObjectName("UwagiDS")
        self.UwagiDS.setMinimumWidth(300)
        label_uwagi_layout.addWidget(self.UwagiDS)
        row2_layout.addLayout(label_uwagi_layout)
        
        row2_layout.addStretch()
        inputs_layout.addLayout(row2_layout)
        
        scroll_area.setWidget(scroll_widget)
        main_layout.addWidget(scroll_area, 1)
        
        # Drugi wiersz - przyciski
        buttons_layout = QtWidgets.QHBoxLayout()
        buttons_layout.setSpacing(10)
        buttons_layout.addStretch()
        
        self.UsunBtDS = QtWidgets.QPushButton(parent=DodajSzafki)
        self.UsunBtDS.setObjectName("UsunBtDS")
        self.UsunBtDS.setText("Usuń szafkę")
        self.UsunBtDS.setMinimumWidth(90)
        buttons_layout.addWidget(self.UsunBtDS)
        
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DodajSzafki)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        buttons_layout.addWidget(self.buttonBox)
        
        main_layout.addLayout(buttons_layout)

        self.retranslateUi(DodajSzafki)
        self.buttonBox.accepted.connect(DodajSzafki.accept) # typ: ignore
        self.buttonBox.rejected.connect(DodajSzafki.reject) # typ: ignore
        QtCore.QMetaObject.connectSlotsByName(DodajSzafki)

    def retranslateUi(self, DodajSzafki):
        _translate = QtCore.QCoreApplication.translate
        DodajSzafki.setWindowTitle(_translate("DodajSzafki", "Edycja szafki"))
        self.MiejsceDS.setWhatsThis(_translate("DodajSzafki", "Wybór miejsca szafki"))
        self.NrSzDS.setWhatsThis(_translate("DodajSzafki", "Numer szafki"))
        self.KodZDS.setWhatsThis(_translate("DodajSzafki", "Kod zamka szafki"))
        self.label_6.setText(_translate("DodajSzafki", "Miejsce"))
        self.label_8.setText(_translate("DodajSzafki", "Nr szafki"))
        self.label_9.setText(_translate("DodajSzafki", "Kod zamka"))
        self.PlecDS.setWhatsThis(_translate("DodajSzafki", "Płeć docelowa szafki"))
        self.label_10.setText(_translate("DodajSzafki", "Płeć docelowa"))
        self.label_kod.setText(_translate("DodajSzafki", "Kod właściciela"))
        self.KodWlascicelaDS.setWhatsThis(_translate("DodajSzafki", "Kod właściciela szafki"))
        self.label_uwagi.setText(_translate("DodajSzafki", "Uwagi"))
        self.UwagiDS.setWhatsThis(_translate("DodajSzafki", "Uwagi do szafki"))
        self.UsunBtDS.setText(_translate("DodajSzafki", "Usuń szafkę"))
        self.StatusSzDS.setWhatsThis(_translate("DodajSzafki", "Status szafki"))
        self.label_11.setText(_translate("DodajSzafki", "Status szafki"))
        self.buttonBox.button(self.buttonBox.StandardButton.Ok).setText(_translate("DodajSzafki", "Zapisz"))
        self.buttonBox.button(self.buttonBox.StandardButton.Cancel).setText(_translate("DodajSzafki", "Anuluj"))